#!/bin/bash
docker compose down
# shellcheck disable=SC2046
docker rm $(docker stop $(docker ps -a -q --filter ancestor=frontend-lenya --format="{{.ID}}"))
docker build -t frontend-lenya .
docker compose up -d --remove-orphans